# Generated by Django 4.0.1 on 2022-01-19 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateChatRoom',
            new_name='DirectMessageRoom',
        ),
    ]
